# Generated by Django 6.1 on 2026-08-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_artist_verification_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file_low',
            field=models.FileField(blank=True, null=True, upload_to='songs/low/'),
        ),
    ]
