# Generated by Django 6.1 on 2026-08-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('free', 'free'), ('silver', 'silver'), ('gold', 'gold')], max_length=20, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'subscription price',
                'verbose_name_plural': 'subscription prices',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('free', 'free'), ('silver', 'silver'), ('gold', 'gold')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('payment_gateway', models.CharField(blank=True, max_length=50)),
                ('payment_data', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
